##
# Load Antigen
#
source /usr/share/zsh/share/antigen.zsh

##
# Load libraries
#
antigen use oh-my-zsh

##
# Load Antigen theme
#
antigen theme nanotech

##
# Load documented plugins from oh-my-zsh repository: https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins
#
antigen bundle adb
#antigen bundle apache2-macports
antigen bundle archlinux
#antigen bundle asdf
#antigen bundle autojump
#antigen bundle autopep8
antigen bundle aws
antigen bundle bower
#antigen bundle brew
#antigen bundle bundler
#antigen bundle cabal
#antigen bundle cake
#antigen bundle capistrano
#antigen bundle cask
antigen bundle catimg
#antigen bundle celery
#antigen bundle chruby
#antigen bundle chucknorris
#antigen bundle command-not-found
antigen bundle Composer
#antigen bundle cloudapp
#antigen bundle coffee
antigen bundle common-aliases
antigen bundle compleat
#antigen bundle cpanm
#antigen bundle debian
antigen bundle dircycle
antigen bundle dirhistory
antigen bundle dirpersist
#antigen bundle django
#antigen bundle dnf
#antigen bundle docker
antigen bundle encode64
#antigen bundle fabric
#antigen bundle fbterm
#antigen bundle Forklift
#antigen bundle fasd
#antigen bundle gas
#antigen bundle geeknote
antigen bundle gem
antigen bundle gpg-agent
#antigen bundle git
antigen bundle gitfast
antigen bundle git-extras
antigen bundle git-flow
#antigen bundle git-flow-avh
#antigen bundle git-hubflow
antigen bundle git_remote_branch
antigen bundle github
#antigen bundle gradle
#antigen bundle grails
#antigen bundle httpie
antigen bundle history
#antigen bundle jira
antigen bundle jsontools
#antigen bundle knife
#antigen bundle laravel4
antigen bundle last-working-dir
#antigen bundle lein
#antigen bundle lighthouse
antigen bundle lol
#antigen bundle macports
#antigen bundle mercurial
#antigen bundle meteor
#antigen bundle mvn
#antigen bundle mysql-macports
#antigen bundle nanoc
#antigen bundle ng
antigen bundle node
antigen bundle npm
antigen bundle nyan
#antigen bundle osx
#antigen bundle pass
antigen bundle per-directory-history
#antigen bundle perl
antigen bundle perms
#antigen bundle pep8
#antigen bundle phing
antigen bundle pip
#antigen bundle pod
#antigen bundle pow
#antigen bundle powify
#antigen bundle pyenv
#antigen bundle pylint
antigen bundle python
antigen bundle rails
#antigen bundle rand-quote
#antigen bundle redis-cli
antigen bundle repo
antigen bundle ruby
antigen bundle rvm
#antigen bundle sbt
#antigen bundle scala
#antigen bundle screen
#antigen bundle sprunge
antigen bundle ssh-agent
#antigen bundle sublime
antigen bundle sudo
#antigen bundle supervisor
#antigen bundle suse
#antigen bundle svn-fast-info
#antigen bundle svn
#antigen bundle symfony2
antigen bundle systemd
#antigen bundle taskwarrior
#antigen bundle terminalapp
antigen bundle terminitor
#antigen bundle textmate
#antigen bundle tig
#antigen bundle thor
antigen bundle tmux
antigen bundle tmuxinator
#antigen bundle tugboat
antigen bundle urltools
antigen bundle vagrant
antigen bundle vi-mode
#antigen bundle virtualenvwrapper
antigen bundle web-search
#antigen bundle yii2
#antigen bundle yii
#antigen bundle yum
#antigen bundle zeus
#antigen bundle wd
#
# Load additional undocumented plugins from oh-my-zsh repository: https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins
#
#antigen bundle adb
#antigen bundle ant
#antigen bundle apache2-macports
#antigen bundle arcanist
#antigen bundle archlinux
#antigen bundle asdf
#antigen bundle autoenv
#antigen bundle autojump
#antigen bundle autopep8
#antigen bundle aws
#antigen bundle battery
#antigen bundle bbedit
#antigen bundle bgnotify
#antigen bundle boot2docker
#antigen bundle bower
#antigen bundle branch
#antigen bundle brew
#antigen bundle bundler
#antigen bundle bwana
#antigen bundle cabal
#antigen bundle cake
#antigen bundle cakephp3
#antigen bundle capistrano
#antigen bundle cargo
#antigen bundle cask
#antigen bundle catimg
#antigen bundle celery
#antigen bundle chruby
#antigen bundle chucknorris
#antigen bundle cloudapp
#antigen bundle codeclimate
#antigen bundle coffee
#antigen bundle colemak
#antigen bundle colored-man-pages
#antigen bundle colorize
#antigen bundle command-not-found
#antigen bundle common-aliases
#antigen bundle compleat
#antigen bundle composer
#antigen bundle copybuffer
#antigen bundle copydir
#antigen bundle copyfile
#antigen bundle cp
#antigen bundle cpanm
#antigen bundle debian
#antigen bundle dircycle
#antigen bundle dirhistory
#antigen bundle dirpersist
#antigen bundle django
#antigen bundle dnf
#antigen bundle docker-compose
#antigen bundle docker
#antigen bundle dotenv
#antigen bundle droplr
#antigen bundle emacs
#antigen bundle ember-cli
#antigen bundle emoji-clock
#antigen bundle emoji
#antigen bundle emotty
#antigen bundle encode64
#antigen bundle extract
#antigen bundle fabric
#antigen bundle fancy-ctrl-z
#antigen bundle fasd
#antigen bundle fastfile
#antigen bundle fbterm
#antigen bundle fedora
#antigen bundle firewalld
#antigen bundle forklift
#antigen bundle fossil
#antigen bundle frontend-search
#antigen bundle gas
#antigen bundle gb
#antigen bundle geeknote
#antigen bundle gem
#antigen bundle git-extras
#antigen bundle git-flow-avh
#antigen bundle git-flow
#antigen bundle git-hubflow
#antigen bundle git-prompt
#antigen bundle git-remote-branch
#antigen bundle git
#antigen bundle gitfast
#antigen bundle github
#antigen bundle gitignore
#antigen bundle glassfish
#antigen bundle globalias
#antigen bundle gnu-utils
#antigen bundle go
#antigen bundle golang
#antigen bundle gpg-agent
#antigen bundle gradle
#antigen bundle grails
#antigen bundle grunt
#antigen bundle gulp
#antigen bundle heroku
#antigen bundle history-substring-search
#antigen bundle history
#antigen bundle httpie
#antigen bundle iwhois
#antigen bundle jake-node
#antigen bundle jhbuild
#antigen bundle jira
#antigen bundle jruby
#antigen bundle jsontools
#antigen bundle jump
#antigen bundle kate
#antigen bundle kitchen
#antigen bundle knife
#antigen bundle knife_ssh
#antigen bundle kubectl
#antigen bundle laravel
#antigen bundle laravel4
#antigen bundle laravel5
#antigen bundle last-working-dir
#antigen bundle lein
#antigen bundle lighthouse
#antigen bundle lol
#antigen bundle macports
#antigen bundle man
#antigen bundle marked2
#antigen bundle mercurial
#antigen bundle meteor
#antigen bundle mix-fast
#antigen bundle mix
#antigen bundle mosh
#antigen bundle mvn
#antigen bundle mysql-macports
#antigen bundle n98-magerun
#antigen bundle nanoc
#antigen bundle ng
#antigen bundle nmap
#antigen bundle node
#antigen bundle nomad
#antigen bundle npm
#antigen bundle nvm
#antigen bundle nyan
#antigen bundle osx
#antigen bundle pass
#antigen bundle paver
#antigen bundle pep8
#antigen bundle per-directory-history
#antigen bundle perl
#antigen bundle perms
#antigen bundle phing
#antigen bundle pip
#antigen bundle pj
#antigen bundle pod
#antigen bundle postgres
#antigen bundle pow
#antigen bundle powder
#antigen bundle powify
#antigen bundle profiles
#antigen bundle pyenv
#antigen bundle pylint
#antigen bundle python
#antigen bundle rails
#antigen bundle rake-fast
#antigen bundle rake
#antigen bundle rand-quote
#antigen bundle rbenv
#antigen bundle rbfu
#antigen bundle react-native
#antigen bundle rebar
#antigen bundle redis-cli
#antigen bundle repo
#antigen bundle rsync
#antigen bundle ruby
#antigen bundle rust
#antigen bundle rvm
#antigen bundle safe-paste
#antigen bundle sbt
#antigen bundle scala
#antigen bundle scd
#antigen bundle screen
#antigen bundle scw
#antigen bundle sfffe
#antigen bundle shrink-path
#antigen bundle singlechar
#antigen bundle spring
#antigen bundle sprunge
#antigen bundle ssh-agent
#antigen bundle stack
#antigen bundle sublime
#antigen bundle sudo
#antigen bundle supervisor
#antigen bundle suse
#antigen bundle svn-fast-info
#antigen bundle svn
#antigen bundle swiftpm
#antigen bundle symfony
#antigen bundle symfony2
#antigen bundle systemadmin
#antigen bundle systemd
#antigen bundle taskwarrior
#antigen bundle terminalapp
#antigen bundle terminitor
#antigen bundle terraform
#antigen bundle textastic
#antigen bundle textmate
#antigen bundle thefuck
#antigen bundle themes
#antigen bundle thor
#antigen bundle tig
#antigen bundle tmux-cssh
#antigen bundle tmux
#antigen bundle tmuxinator
#antigen bundle torrent
#antigen bundle tugboat
#antigen bundle ubuntu
#antigen bundle urltools
#antigen bundle vagrant
#antigen bundle vault
#antigen bundle vi-mode
#antigen bundle vim-interaction
#antigen bundle virtualenv
#antigen bundle virtualenvwrapper
#antigen bundle vundle
#antigen bundle wakeonlan
#antigen bundle wd
#antigen bundle web-search
#antigen bundle wp-cli
#antigen bundle xcode
#antigen bundle yarn
#antigen bundle yii
#antigen bundle yii2
#antigen bundle yum
#antigen bundle z
#antigen bundle zeus
#antigen bundle zsh-navigation-tools
#antigen bundle zsh_reload

##
# Syntax highlighting bundle.
#
antigen bundle zsh-users/zsh-syntax-highlighting

##
# TMUX config
#
ZSH_TMUX_AUTOSTART=true

##
# Complete setup
#
antigen apply
